### ISSUE TITLE
useChannel performance optimization

### ISSUE THREAD

**Issue by asimkt** [mayteio/use-pusher#29]
The code,
```
useEffect(() => {
    /** Return early if there's no client */
    if (!client) return;

    /** Return early and warn if there's no channel */
    if (!channelName) {
      console.warn(NO_CHANNEL_NAME_WARNING);
      return;
    }

    /** Subscribe to channel and set it in state */
    const pusherChannel = client.subscribe(channelName);
    setChannel(pusherChannel as T);

    /** Cleanup on unmount/re-render */
    return () => client?.unsubscribe(channelName);
  }, [channelName, client]);
```
will keep connecting to the channel even if the app is already connected to the same channel before. Can we have some kind of check before subscribing to the same channel?

Something like:
```
   ...
   if (!channelName) {
      console.warn(NO_CHANNEL_NAME_WARNING);
      return;
    }
   if (isSubscribed(channelName)) {
      return;
    }

    /** Subscribe to channel and set it in state */
    const pusherChannel = client.subscribe(channelName);
    setChannel(pusherChannel as T);
    // Keep record of connected channels
    addChannelToTheMap(channelName)
    ...
...
```

Or was this a design decision? In that case, if the user keep subscribing to the same channel, what she should do to remove the extra connections?

**Comment by mayteio** [comment]
Hey @asimkt, thanks for bringing this up!

I could be totally wrong, but internally `pusher-js` maintains an object of channels the user is subscribed to. So calling `useChannel('my-channel')` in multiple places subscribes to the same channel, and callbacks are connected to the same subscription.

Additionally, this effect should only re-run (by design) when either;
- `channelName` (string) changes, in which case it should unsubscribe and resubscribe to the new channel name, or 
- `client` (state) changes, which shouldn't happen too often (only, for example, when another authorizer is passed to it,, in which case it needs to resubscribe). 

Is this an issue that you're having, or just a proactive improvement? If the former, please provide a codesandbox I can have a look at!

**Comment by asimkt** [comment]
Seems like pusher-js is not keeping the object of channels and this leads to multiple different subscriptions. 
In my case, 
- The client is only rendered on top. (Like you said, not changing much)
- I'm trying to connect to the same channel name (same string) in different components. 

And in the pusher debug console, I can see multiple connections happening.  Let me try to create a sandbox.

**Comment by asimkt** [comment]
pusher-js is keeping the subscribed channels. https://github.com/pusher/pusher-js/blob/9152c97631d08d428d36ded807b8c81ef7c008d3/src/core/channels/channel.ts#L96. I will dig deeper on what happened after some time. Closing this down since I think this may not be directly related to the use-pusher library

**Comment by mayteio** [comment]
Let me know if I can help with anything. Cheers
